# Generated by Django 3.2.3 on 2021-05-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='')),
                ('img', models.CharField(max_length=100, verbose_name='')),
                ('bateria', models.CharField(max_length=100, verbose_name='')),
                ('peso', models.CharField(max_length=100, verbose_name='')),
                ('pantalla', models.CharField(max_length=100, verbose_name='')),
                ('tasa_ref', models.CharField(max_length=100, verbose_name='')),
                ('proce', models.CharField(max_length=100, verbose_name='')),
                ('proce_nucleos', models.CharField(max_length=100, verbose_name='')),
                ('proce_hilos', models.CharField(max_length=100, verbose_name='')),
                ('proce_freq', models.CharField(max_length=100, verbose_name='')),
                ('proce_freq_turbo', models.CharField(max_length=100, verbose_name='')),
                ('gpu', models.CharField(max_length=100, verbose_name='')),
                ('gpudedi', models.CharField(max_length=100, verbose_name='')),
                ('so', models.CharField(max_length=100, verbose_name='')),
                ('almace', models.CharField(max_length=100, verbose_name='')),
                ('ram', models.CharField(max_length=100, verbose_name='')),
                ('puertos', models.CharField(max_length=100, verbose_name='')),
                ('dimenciones', models.CharField(max_length=100, verbose_name='')),
                ('aplicaciones', models.CharField(max_length=100, verbose_name='')),
                ('gamming', models.CharField(max_length=100, verbose_name='')),
                ('movilidad', models.CharField(max_length=100, verbose_name='')),
                ('score_gpu', models.CharField(max_length=100, verbose_name='')),
                ('score_cpu', models.CharField(max_length=100, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Inicio')),
                ('typr', models.CharField(max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(max_length=15, verbose_name='Estado')),
                ('finish', models.DateTimeField(verbose_name='Termino')),
            ],
        ),
    ]
