# Generated by Django 3.2.3 on 2021-05-26 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Inicio')),
                ('type', models.CharField(max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(max_length=15, verbose_name='Estado')),
                ('finish', models.CharField(max_length=50, verbose_name='Termino')),
                ('items', models.IntegerField(default=0, verbose_name='Items')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('img', models.CharField(max_length=100, verbose_name='img')),
                ('bateria', models.CharField(max_length=100, verbose_name='Bateria')),
                ('peso', models.CharField(max_length=100, verbose_name='Peso')),
                ('pantalla', models.CharField(max_length=100, verbose_name='Pantalla')),
                ('tasa_ref', models.CharField(max_length=100, verbose_name='Tasa Ref')),
                ('proce', models.CharField(max_length=100, verbose_name='CPU')),
                ('proce_nucleos', models.CharField(max_length=100, verbose_name='CPUNucleos')),
                ('proce_hilos', models.CharField(max_length=100, verbose_name='CPUHilos')),
                ('proce_freq', models.CharField(max_length=100, verbose_name='CPUFreq')),
                ('proce_freq_turbo', models.CharField(max_length=100, verbose_name='CPUTurbo')),
                ('gpu', models.CharField(max_length=100, verbose_name='GPU')),
                ('gpuDedi', models.CharField(max_length=100, verbose_name='GPUDed')),
                ('so', models.CharField(max_length=100, verbose_name='S.O.')),
                ('almace', models.CharField(max_length=100, verbose_name='Almacenamiento')),
                ('ram', models.CharField(max_length=100, verbose_name='RAM')),
                ('puertos', models.CharField(max_length=100, verbose_name='Puertos')),
                ('dimensiones', models.CharField(max_length=100, verbose_name='Dimen')),
                ('aplicaciones', models.CharField(max_length=100, verbose_name='Aplicaciones')),
                ('gamming', models.CharField(max_length=100, verbose_name='Gaming')),
                ('movilidad', models.CharField(max_length=100, verbose_name='Movilidad')),
                ('score_gpu', models.IntegerField(verbose_name='PuntajeGPU')),
                ('score_cpu', models.IntegerField(verbose_name='PuntajeCPU')),
                ('precio', models.CharField(max_length=50, verbose_name='Precio')),
                ('precioint', models.IntegerField(default=0, verbose_name='PrecioInt')),
                ('puntaje1', models.IntegerField(default=0, verbose_name='Puntaje1')),
                ('puntaje2', models.IntegerField(default=0, verbose_name='Puntaje1')),
                ('solotodo_id', models.CharField(max_length=51, verbose_name='ID Solotodo')),
                ('id_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntbk.rutina')),
            ],
        ),
    ]
