# Generated by Django 3.2.3 on 2021-05-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntbk', '0002_note_id_rutina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rutina',
            old_name='typr',
            new_name='type',
        ),
    ]
