# Generated by Django 3.2.3 on 2021-05-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntbk', '0002_note_dataj'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ramint',
            field=models.IntegerField(default=0, verbose_name='RAM INT'),
        ),
        migrations.AlterField(
            model_name='note',
            name='puntaje2',
            field=models.IntegerField(default=0, verbose_name='Puntaje2'),
        ),
    ]
