# Generated by Django 3.2.3 on 2021-05-24 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntbk', '0004_auto_20210524_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id_rutina',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ntbk.rutina'),
        ),
    ]
