# Generated by Django 3.2.3 on 2021-05-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntbk', '0005_alter_note_id_rutina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='id_rutina',
        ),
    ]
