# Generated by Django 3.2.3 on 2021-05-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntbk', '0006_remove_note_id_rutina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='precioint',
            field=models.IntegerField(blank=True, verbose_name='Puntaje CPU'),
        ),
    ]
