# Generated by Django 3.2.3 on 2021-05-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntbk', '0007_alter_note_precioint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='precioint',
        ),
    ]
