# Generated by Django 3.2.3 on 2021-05-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntbk', '0008_remove_note_precioint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='dimenciones',
            new_name='dimensiones',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='gpudedi',
            new_name='gpuDedi',
        ),
    ]
