# Generated by Django 3.2.3 on 2021-05-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntbk', '0011_note_solotodo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='id_rutina',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ntbk.rutina'),
            preserve_default=False,
        ),
    ]
