# Generated by Django 3.2.3 on 2021-05-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntbk', '0016_alter_rutina_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='items',
            field=models.IntegerField(default=0, verbose_name='Items'),
        ),
    ]
