# Generated by Django 3.2.3 on 2021-05-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntbk', '0017_alter_rutina_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='precioint',
            field=models.IntegerField(default=0, verbose_name='Precio Integer'),
        ),
    ]
